### ISSUE TITLE
Precios y lista de precios

### ISSUE THREAD

**Issue by MattiRuiz** [MattiRuiz/vite-catalogo-marcablanca-front#5]
- [x] Incluir los precios en el catálogo
- [x] Hacer funcionar el switch que permite mostrar/ocultar los precios
- [x] Hacer la función de mostrar el precio revendedor en el catálogo
- [x] Utilizar un modulo que permita pasar a pdf la lista de precios

**Comment by MattiRuiz** [comment]
Finalizado por el FAQS @faacuromano , issue cerrado

**Comment by faacuromano** [comment]
fak asss
